name: Continuous Integration

# for reference:
# https://github.community/t/dont-run-on-tag-creation/137469/7
on: 
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    # MONITOR(cavcrosby): similar issue as it appears the ubuntu image includes a go binary:
    # https://github.com/actions/setup-go/issues/104
    - name: Set up Go for root
      run: |
        sudo ln --symbolic --force "$(command -v go)" "$(sudo --shell command -v go)"
        sudo go version
        
    - name: Display roots Go env
      run: sudo go env

    - name: Install dependencies
      run: sudo apt-get install build-essential debootstrap --assume-yes

    - name: Build
      run: |
        make debcomprt
        make install

    - name: Run Unit/Integration Tests
      run: make test
    
  upload-artifact:
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up Go for root
      run: |
        sudo ln --symbolic --force "$(command -v go)" "$(sudo --shell command -v go)"
        sudo go version
        
    - name: Display roots Go env
      run: sudo go env

    - name: Install dependencies
      run: sudo apt-get install build-essential debootstrap --assume-yes

    - name: Build
      run: make debcomprt
    
    - uses: actions/upload-artifact@v2
      with:
        name: debcomprt
        path: ./build/debcomprt
        if-no-files-found: error
