name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Set up Go for root
      run: |
        sudo ln --symbolic --force "$(command -v go)" "$(sudo --shell command -v go)"
        sudo go version

    - name: Install make
      run: sudo apt-get install build-essential --assume-yes

    - name: Build
      run: |
        make setup
        make debcomprt
        make install
        
    - name: Find Roots Go Env
      run: sudo go env

    - name: Run Unit/Integration Tests
      run: sudo --preserve-env make test
